language: python

python:
  - "3.6"

os: linux

sudo: enabled

branches:
  only:
    - dev-live

jobs:
  include:
    - stage: deploy
      script: "./sayTime/saytime.py"
    - stage: test
      script: "./sayTime/saytime-test.py"

env:
  global:
  - USER: "pktanksali"
  - EMAIL: "pktanksali@gmail.com"
  - REPO: "travisHandsOn"
  - FILES: ".travis.yml sayTime/saytime-test.py sayTime/saytime.py"
  - GH_REPO: "github.com/${USER}/${REPO}.git"
  - secure: "ewwGtahVKNxdvP-xeWmGMw"

after_success:
  - MESSAGE: $(git log --format=%B -n 1 $TRAVIS_COMMIT)
  - git clone git://${GH_REPO}
  - mv -f ${FILES} ${REPO}
  - cd ${REPO}
  - git remote
  - git config user.email ${EMAIL}
  - git config user.name ${USER}
  - git add ${FILES}
  - git commit -m ${MESSAGE}
  - git push "https://${TRAVIS_SECURE_TOKEN_NAME}@${GH_REPO}" master > /dev/null 2>&1
